package com.nachc.dba.twitternews

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.webkit.WebViewClient
import com.nachc.dba.R
import com.nachc.dba.util.isInternetAvailable
import kotlinx.android.synthetic.main.fragment_twitter_news.*

class TwitterNewsFragment : Fragment() {

    // html code generated by Twitter for Websites, for an "embedded timeline"
    val data = "<a class=\"twitter-timeline\" data-lang=\"en\" data-theme=\"light\" href=\"https://twitter.com/dublinbusnews?ref_src=twsrc%5Etfw\">Tweets by dublinbusnews</a> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_twitter_news, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        webView.apply {
            webViewClient = WebViewClient()
            settings.javaScriptEnabled = true
        }

        isInternetAvailable(requireContext()) { isConnected ->
            if (isConnected) {
                requireActivity().runOnUiThread(kotlinx.coroutines.Runnable {
                    webView.loadData(data, "text/html", "utf-8")
                })
            }
        }
    }
}